# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import connect_api_pb2 as connect__api__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in connect_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ConnectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.KnowledgeConnect = channel.unary_unary(
                '/connect_api.ConnectService/KnowledgeConnect',
                request_serializer=connect__api__pb2.KnowledgeConnectRequest.SerializeToString,
                response_deserializer=connect__api__pb2.KnowledgeConnectResponse.FromString,
                _registered_method=True)
        self.ActionConnect = channel.unary_unary(
                '/connect_api.ConnectService/ActionConnect',
                request_serializer=connect__api__pb2.ActionConnectRequest.SerializeToString,
                response_deserializer=connect__api__pb2.ActionConnectResponse.FromString,
                _registered_method=True)
        self.GetConnectorFiles = channel.unary_unary(
                '/connect_api.ConnectService/GetConnectorFiles',
                request_serializer=connect__api__pb2.GetConnectorFilesRequest.SerializeToString,
                response_deserializer=connect__api__pb2.GetConnectorFilesResponse.FromString,
                _registered_method=True)


class ConnectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def KnowledgeConnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActionConnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectorFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'KnowledgeConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.KnowledgeConnect,
                    request_deserializer=connect__api__pb2.KnowledgeConnectRequest.FromString,
                    response_serializer=connect__api__pb2.KnowledgeConnectResponse.SerializeToString,
            ),
            'ActionConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.ActionConnect,
                    request_deserializer=connect__api__pb2.ActionConnectRequest.FromString,
                    response_serializer=connect__api__pb2.ActionConnectResponse.SerializeToString,
            ),
            'GetConnectorFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectorFiles,
                    request_deserializer=connect__api__pb2.GetConnectorFilesRequest.FromString,
                    response_serializer=connect__api__pb2.GetConnectorFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'connect_api.ConnectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('connect_api.ConnectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConnectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def KnowledgeConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connect_api.ConnectService/KnowledgeConnect',
            connect__api__pb2.KnowledgeConnectRequest.SerializeToString,
            connect__api__pb2.KnowledgeConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActionConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connect_api.ConnectService/ActionConnect',
            connect__api__pb2.ActionConnectRequest.SerializeToString,
            connect__api__pb2.ActionConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectorFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/connect_api.ConnectService/GetConnectorFiles',
            connect__api__pb2.GetConnectorFilesRequest.SerializeToString,
            connect__api__pb2.GetConnectorFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
