# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rapida.artifacts.protos.provider_api_pb2 as provider__api__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in provider_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ProviderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllProvider = channel.unary_unary(
                '/provider_api.ProviderService/GetAllProvider',
                request_serializer=provider__api__pb2.GetAllProviderRequest.SerializeToString,
                response_deserializer=provider__api__pb2.GetAllProviderResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/provider_api.ProviderService/GetModel',
                request_serializer=provider__api__pb2.GetModelRequest.SerializeToString,
                response_deserializer=provider__api__pb2.GetModelResponse.FromString,
                _registered_method=True)
        self.GetAllModel = channel.unary_unary(
                '/provider_api.ProviderService/GetAllModel',
                request_serializer=provider__api__pb2.GetAllModelRequest.SerializeToString,
                response_deserializer=provider__api__pb2.GetAllModelResponse.FromString,
                _registered_method=True)


class ProviderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllProvider,
                    request_deserializer=provider__api__pb2.GetAllProviderRequest.FromString,
                    response_serializer=provider__api__pb2.GetAllProviderResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=provider__api__pb2.GetModelRequest.FromString,
                    response_serializer=provider__api__pb2.GetModelResponse.SerializeToString,
            ),
            'GetAllModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllModel,
                    request_deserializer=provider__api__pb2.GetAllModelRequest.FromString,
                    response_serializer=provider__api__pb2.GetAllModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'provider_api.ProviderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('provider_api.ProviderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProviderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/provider_api.ProviderService/GetAllProvider',
            provider__api__pb2.GetAllProviderRequest.SerializeToString,
            provider__api__pb2.GetAllProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/provider_api.ProviderService/GetModel',
            provider__api__pb2.GetModelRequest.SerializeToString,
            provider__api__pb2.GetModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/provider_api.ProviderService/GetAllModel',
            provider__api__pb2.GetAllModelRequest.SerializeToString,
            provider__api__pb2.GetAllModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
