# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: provider-api.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rapida.artifacts.protos.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12provider-api.proto\x12\x0cprovider_api\x1a\x0c\x63ommon.proto\"2\n\x12GetAllModelRequest\x12\x1c\n\tcriterias\x18\x01 \x03(\x0b\x32\t.Criteria\"R\n\x13GetAllModelResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1c\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x0e.ProviderModel\"&\n\x0fGetModelRequest\x12\x13\n\x07modelId\x18\x01 \x01(\x04\x42\x02\x30\x01\"P\n\x10GetModelResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1d\n\x05model\x18\x03 \x01(\x0b\x32\x0e.ProviderModel\"\x17\n\x15GetAllProviderRequest\"P\n\x16GetAllProviderResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x17\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\t.Provider2\x8d\x02\n\x0fProviderService\x12[\n\x0eGetAllProvider\x12#.provider_api.GetAllProviderRequest\x1a$.provider_api.GetAllProviderResponse\x12I\n\x08GetModel\x12\x1d.provider_api.GetModelRequest\x1a\x1e.provider_api.GetModelResponse\x12R\n\x0bGetAllModel\x12 .provider_api.GetAllModelRequest\x1a!.provider_api.GetAllModelResponseB7Z5github.com/lexatic/web-backend/protos/lexatic-backendb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'provider_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/lexatic/web-backend/protos/lexatic-backend'
  _globals['_GETMODELREQUEST'].fields_by_name['modelId']._loaded_options = None
  _globals['_GETMODELREQUEST'].fields_by_name['modelId']._serialized_options = b'0\001'
  _globals['_GETALLMODELREQUEST']._serialized_start=50
  _globals['_GETALLMODELREQUEST']._serialized_end=100
  _globals['_GETALLMODELRESPONSE']._serialized_start=102
  _globals['_GETALLMODELRESPONSE']._serialized_end=184
  _globals['_GETMODELREQUEST']._serialized_start=186
  _globals['_GETMODELREQUEST']._serialized_end=224
  _globals['_GETMODELRESPONSE']._serialized_start=226
  _globals['_GETMODELRESPONSE']._serialized_end=306
  _globals['_GETALLPROVIDERREQUEST']._serialized_start=308
  _globals['_GETALLPROVIDERREQUEST']._serialized_end=331
  _globals['_GETALLPROVIDERRESPONSE']._serialized_start=333
  _globals['_GETALLPROVIDERRESPONSE']._serialized_end=413
  _globals['_PROVIDERSERVICE']._serialized_start=416
  _globals['_PROVIDERSERVICE']._serialized_end=685
# @@protoc_insertion_point(module_scope)
