# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rapida.artifacts.protos.common_pb2 as common__pb2
import talk_api_pb2 as talk__api__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in talk_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TalkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssistantMessaging = channel.unary_stream(
                '/talk_api.TalkService/AssistantMessaging',
                request_serializer=talk__api__pb2.AssistantMessagingRequest.SerializeToString,
                response_deserializer=talk__api__pb2.AssistantMessagingResponse.FromString,
                _registered_method=True)
        self.AssistantTalk = channel.stream_stream(
                '/talk_api.TalkService/AssistantTalk',
                request_serializer=talk__api__pb2.AssistantMessagingRequest.SerializeToString,
                response_deserializer=talk__api__pb2.AssistantMessagingResponse.FromString,
                _registered_method=True)
        self.GetAllAssistantConversation = channel.unary_unary(
                '/talk_api.TalkService/GetAllAssistantConversation',
                request_serializer=common__pb2.GetAllAssistantConversationRequest.SerializeToString,
                response_deserializer=common__pb2.GetAllAssistantConversationResponse.FromString,
                _registered_method=True)
        self.GetAllConversationMessage = channel.unary_unary(
                '/talk_api.TalkService/GetAllConversationMessage',
                request_serializer=common__pb2.GetAllConversationMessageRequest.SerializeToString,
                response_deserializer=common__pb2.GetAllConversationMessageResponse.FromString,
                _registered_method=True)
        self.CreateMessageMetric = channel.unary_unary(
                '/talk_api.TalkService/CreateMessageMetric',
                request_serializer=talk__api__pb2.CreateMessageMetricRequest.SerializeToString,
                response_deserializer=talk__api__pb2.CreateMessageMetricResponse.FromString,
                _registered_method=True)
        self.CreateConversationMetric = channel.unary_unary(
                '/talk_api.TalkService/CreateConversationMetric',
                request_serializer=talk__api__pb2.CreateConversationMetricRequest.SerializeToString,
                response_deserializer=talk__api__pb2.CreateConversationMetricResponse.FromString,
                _registered_method=True)
        self.InitiateAssistantTalk = channel.unary_unary(
                '/talk_api.TalkService/InitiateAssistantTalk',
                request_serializer=talk__api__pb2.InitiateAssistantTalkRequest.SerializeToString,
                response_deserializer=talk__api__pb2.InitiateAssistantTalkResponse.FromString,
                _registered_method=True)
        self.InitiateBulkAssistantTalk = channel.unary_unary(
                '/talk_api.TalkService/InitiateBulkAssistantTalk',
                request_serializer=talk__api__pb2.InitiateBulkAssistantTalkRequest.SerializeToString,
                response_deserializer=talk__api__pb2.InitiateBulkAssistantTalkResponse.FromString,
                _registered_method=True)


class TalkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AssistantMessaging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssistantTalk(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllAssistantConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllConversationMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMessageMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConversationMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateAssistantTalk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateBulkAssistantTalk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TalkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssistantMessaging': grpc.unary_stream_rpc_method_handler(
                    servicer.AssistantMessaging,
                    request_deserializer=talk__api__pb2.AssistantMessagingRequest.FromString,
                    response_serializer=talk__api__pb2.AssistantMessagingResponse.SerializeToString,
            ),
            'AssistantTalk': grpc.stream_stream_rpc_method_handler(
                    servicer.AssistantTalk,
                    request_deserializer=talk__api__pb2.AssistantMessagingRequest.FromString,
                    response_serializer=talk__api__pb2.AssistantMessagingResponse.SerializeToString,
            ),
            'GetAllAssistantConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllAssistantConversation,
                    request_deserializer=common__pb2.GetAllAssistantConversationRequest.FromString,
                    response_serializer=common__pb2.GetAllAssistantConversationResponse.SerializeToString,
            ),
            'GetAllConversationMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllConversationMessage,
                    request_deserializer=common__pb2.GetAllConversationMessageRequest.FromString,
                    response_serializer=common__pb2.GetAllConversationMessageResponse.SerializeToString,
            ),
            'CreateMessageMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessageMetric,
                    request_deserializer=talk__api__pb2.CreateMessageMetricRequest.FromString,
                    response_serializer=talk__api__pb2.CreateMessageMetricResponse.SerializeToString,
            ),
            'CreateConversationMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConversationMetric,
                    request_deserializer=talk__api__pb2.CreateConversationMetricRequest.FromString,
                    response_serializer=talk__api__pb2.CreateConversationMetricResponse.SerializeToString,
            ),
            'InitiateAssistantTalk': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateAssistantTalk,
                    request_deserializer=talk__api__pb2.InitiateAssistantTalkRequest.FromString,
                    response_serializer=talk__api__pb2.InitiateAssistantTalkResponse.SerializeToString,
            ),
            'InitiateBulkAssistantTalk': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateBulkAssistantTalk,
                    request_deserializer=talk__api__pb2.InitiateBulkAssistantTalkRequest.FromString,
                    response_serializer=talk__api__pb2.InitiateBulkAssistantTalkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'talk_api.TalkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('talk_api.TalkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TalkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AssistantMessaging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/talk_api.TalkService/AssistantMessaging',
            talk__api__pb2.AssistantMessagingRequest.SerializeToString,
            talk__api__pb2.AssistantMessagingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssistantTalk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/talk_api.TalkService/AssistantTalk',
            talk__api__pb2.AssistantMessagingRequest.SerializeToString,
            talk__api__pb2.AssistantMessagingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllAssistantConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talk_api.TalkService/GetAllAssistantConversation',
            common__pb2.GetAllAssistantConversationRequest.SerializeToString,
            common__pb2.GetAllAssistantConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllConversationMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talk_api.TalkService/GetAllConversationMessage',
            common__pb2.GetAllConversationMessageRequest.SerializeToString,
            common__pb2.GetAllConversationMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMessageMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talk_api.TalkService/CreateMessageMetric',
            talk__api__pb2.CreateMessageMetricRequest.SerializeToString,
            talk__api__pb2.CreateMessageMetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConversationMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talk_api.TalkService/CreateConversationMetric',
            talk__api__pb2.CreateConversationMetricRequest.SerializeToString,
            talk__api__pb2.CreateConversationMetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiateAssistantTalk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talk_api.TalkService/InitiateAssistantTalk',
            talk__api__pb2.InitiateAssistantTalkRequest.SerializeToString,
            talk__api__pb2.InitiateAssistantTalkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiateBulkAssistantTalk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talk_api.TalkService/InitiateBulkAssistantTalk',
            talk__api__pb2.InitiateBulkAssistantTalkRequest.SerializeToString,
            talk__api__pb2.InitiateBulkAssistantTalkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
