# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tool-api.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rapida.artifacts.protos.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etool-api.proto\x12\x08tool_api\x1a\x0c\x63ommon.proto\"`\n\x0cToolProvider\x12\x0e\n\x02id\x18\x01 \x01(\x04\x42\x02\x30\x01\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\"\x87\x02\n\x04Tool\x12\x0e\n\x02id\x18\x01 \x01(\x04\x42\x02\x30\x01\x12,\n\x0ctoolProvider\x18\x02 \x01(\x0b\x32\x16.tool_api.ToolProvider\x12\x0f\n\x07\x66\x65\x61ture\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\r\n\x05\x61\x63tor\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x46\n\x14\x63onnectConfiguration\x18\x07 \x03(\x0b\x32(.tool_api.Tool.ConnectConfigurationEntry\x1a;\n\x19\x43onnectConfigurationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"N\n\x11GetAllToolRequest\x12\x1b\n\x08paginate\x18\x01 \x01(\x0b\x32\t.Paginate\x12\x1c\n\tcriterias\x18\x02 \x03(\x0b\x32\t.Criteria\"\x87\x01\n\x12GetAllToolResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1c\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x0e.tool_api.Tool\x12\x15\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x06.Error\x12\x1d\n\tpaginated\x18\x05 \x01(\x0b\x32\n.Paginated2V\n\x0bToolService\x12G\n\nGetAllTool\x12\x1b.tool_api.GetAllToolRequest\x1a\x1c.tool_api.GetAllToolResponseB7Z5github.com/lexatic/web-backend/protos/lexatic-backendb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tool_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/lexatic/web-backend/protos/lexatic-backend'
  _globals['_TOOLPROVIDER'].fields_by_name['id']._loaded_options = None
  _globals['_TOOLPROVIDER'].fields_by_name['id']._serialized_options = b'0\001'
  _globals['_TOOL_CONNECTCONFIGURATIONENTRY']._loaded_options = None
  _globals['_TOOL_CONNECTCONFIGURATIONENTRY']._serialized_options = b'8\001'
  _globals['_TOOL'].fields_by_name['id']._loaded_options = None
  _globals['_TOOL'].fields_by_name['id']._serialized_options = b'0\001'
  _globals['_TOOLPROVIDER']._serialized_start=42
  _globals['_TOOLPROVIDER']._serialized_end=138
  _globals['_TOOL']._serialized_start=141
  _globals['_TOOL']._serialized_end=404
  _globals['_TOOL_CONNECTCONFIGURATIONENTRY']._serialized_start=345
  _globals['_TOOL_CONNECTCONFIGURATIONENTRY']._serialized_end=404
  _globals['_GETALLTOOLREQUEST']._serialized_start=406
  _globals['_GETALLTOOLREQUEST']._serialized_end=484
  _globals['_GETALLTOOLRESPONSE']._serialized_start=487
  _globals['_GETALLTOOLRESPONSE']._serialized_end=622
  _globals['_TOOLSERVICE']._serialized_start=624
  _globals['_TOOLSERVICE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
