# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: marketplace-api.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'marketplace-api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
import rapida.clients.protos.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15marketplace-api.proto\x12\x0fmarketplace_api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0c\x63ommon.proto\"T\n\x17GetAllDeploymentRequest\x12\x1b\n\x08paginate\x18\x01 \x01(\x0b\x32\t.Paginate\x12\x1c\n\tcriterias\x18\x02 \x03(\x0b\x32\t.Criteria\"\x81\x04\n\x14SearchableDeployment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nvisibility\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x11\n\tprojectId\x18\x07 \x01(\t\x12\x16\n\x0eorganizationId\x18\x08 \x01(\t\x12\x0b\n\x03tag\x18\x0e \x03(\t\x12\x10\n\x08language\x18\x10 \x01(\t\x12#\n\x0corganization\x18\x11 \x01(\x0b\x32\r.Organization\x12\x0c\n\x04name\x18\x12 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x13 \x01(\t\x12/\n\x0b\x63reatedDate\x18\x14 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bupdatedDate\x18\x15 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\rappAppearance\x18\x18 \x01(\x0b\x32\x17.google.protobuf.Struct\x12.\n\rwebAppearance\x18\x19 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x1b\n\x0fmodelProviderId\x18\x1a \x01(\x04\x42\x02\x30\x01\x12\x19\n\x11modelProviderName\x18\x1b \x01(\t\x12\x1f\n\x0cmodelOptions\x18\x0c \x03(\x0b\x32\t.Metadata\"\xa4\x01\n\x18GetAllDeploymentResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x33\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32%.marketplace_api.SearchableDeployment\x12\x15\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x06.Error\x12\x1d\n\tpaginated\x18\x05 \x01(\x0b\x32\n.Paginated2}\n\x12MarketplaceService\x12g\n\x10GetAllDeployment\x12(.marketplace_api.GetAllDeploymentRequest\x1a).marketplace_api.GetAllDeploymentResponseB7Z5github.com/lexatic/web-backend/protos/lexatic-backendb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'marketplace_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/lexatic/web-backend/protos/lexatic-backend'
  _globals['_SEARCHABLEDEPLOYMENT'].fields_by_name['modelProviderId']._loaded_options = None
  _globals['_SEARCHABLEDEPLOYMENT'].fields_by_name['modelProviderId']._serialized_options = b'0\001'
  _globals['_GETALLDEPLOYMENTREQUEST']._serialized_start=119
  _globals['_GETALLDEPLOYMENTREQUEST']._serialized_end=203
  _globals['_SEARCHABLEDEPLOYMENT']._serialized_start=206
  _globals['_SEARCHABLEDEPLOYMENT']._serialized_end=719
  _globals['_GETALLDEPLOYMENTRESPONSE']._serialized_start=722
  _globals['_GETALLDEPLOYMENTRESPONSE']._serialized_end=886
  _globals['_MARKETPLACESERVICE']._serialized_start=888
  _globals['_MARKETPLACESERVICE']._serialized_end=1013
# @@protoc_insertion_point(module_scope)
