# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rapida.clients.protos.marketplace_api_pb2 as marketplace__api__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in marketplace_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketplaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllDeployment = channel.unary_unary(
                '/marketplace_api.MarketplaceService/GetAllDeployment',
                request_serializer=marketplace__api__pb2.GetAllDeploymentRequest.SerializeToString,
                response_deserializer=marketplace__api__pb2.GetAllDeploymentResponse.FromString,
                _registered_method=True)


class MarketplaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketplaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllDeployment,
                    request_deserializer=marketplace__api__pb2.GetAllDeploymentRequest.FromString,
                    response_serializer=marketplace__api__pb2.GetAllDeploymentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace_api.MarketplaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace_api.MarketplaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketplaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace_api.MarketplaceService/GetAllDeployment',
            marketplace__api__pb2.GetAllDeploymentRequest.SerializeToString,
            marketplace__api__pb2.GetAllDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
