# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rapida.clients.protos.provider_api_pb2 as provider__api__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in provider_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProviderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllToolProvider = channel.unary_unary(
                '/provider_api.ProviderService/GetAllToolProvider',
                request_serializer=provider__api__pb2.GetAllToolProviderRequest.SerializeToString,
                response_deserializer=provider__api__pb2.GetAllToolProviderResponse.FromString,
                _registered_method=True)
        self.GetAllModelProvider = channel.unary_unary(
                '/provider_api.ProviderService/GetAllModelProvider',
                request_serializer=provider__api__pb2.GetAllModelProviderRequest.SerializeToString,
                response_deserializer=provider__api__pb2.GetAllModelProviderResponse.FromString,
                _registered_method=True)


class ProviderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllToolProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllModelProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllToolProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllToolProvider,
                    request_deserializer=provider__api__pb2.GetAllToolProviderRequest.FromString,
                    response_serializer=provider__api__pb2.GetAllToolProviderResponse.SerializeToString,
            ),
            'GetAllModelProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllModelProvider,
                    request_deserializer=provider__api__pb2.GetAllModelProviderRequest.FromString,
                    response_serializer=provider__api__pb2.GetAllModelProviderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'provider_api.ProviderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('provider_api.ProviderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProviderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllToolProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/provider_api.ProviderService/GetAllToolProvider',
            provider__api__pb2.GetAllToolProviderRequest.SerializeToString,
            provider__api__pb2.GetAllToolProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllModelProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/provider_api.ProviderService/GetAllModelProvider',
            provider__api__pb2.GetAllModelProviderRequest.SerializeToString,
            provider__api__pb2.GetAllModelProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
