# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rapida.clients.protos.sendgrid_api_pb2 as sendgrid__api__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sendgrid_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SendgridServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WelcomeEmail = channel.unary_unary(
                '/integration_api.SendgridService/WelcomeEmail',
                request_serializer=sendgrid__api__pb2.WelcomeEmailRequest.SerializeToString,
                response_deserializer=sendgrid__api__pb2.WelcomeEmailResponse.FromString,
                _registered_method=True)
        self.ResetPasswordEmail = channel.unary_unary(
                '/integration_api.SendgridService/ResetPasswordEmail',
                request_serializer=sendgrid__api__pb2.ResetPasswordEmailRequest.SerializeToString,
                response_deserializer=sendgrid__api__pb2.ResetPasswordEmailResponse.FromString,
                _registered_method=True)
        self.InviteMemberEmail = channel.unary_unary(
                '/integration_api.SendgridService/InviteMemberEmail',
                request_serializer=sendgrid__api__pb2.InviteMemeberEmailRequest.SerializeToString,
                response_deserializer=sendgrid__api__pb2.InviteMemeberEmailResponse.FromString,
                _registered_method=True)


class SendgridServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WelcomeEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPasswordEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InviteMemberEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendgridServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WelcomeEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.WelcomeEmail,
                    request_deserializer=sendgrid__api__pb2.WelcomeEmailRequest.FromString,
                    response_serializer=sendgrid__api__pb2.WelcomeEmailResponse.SerializeToString,
            ),
            'ResetPasswordEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPasswordEmail,
                    request_deserializer=sendgrid__api__pb2.ResetPasswordEmailRequest.FromString,
                    response_serializer=sendgrid__api__pb2.ResetPasswordEmailResponse.SerializeToString,
            ),
            'InviteMemberEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteMemberEmail,
                    request_deserializer=sendgrid__api__pb2.InviteMemeberEmailRequest.FromString,
                    response_serializer=sendgrid__api__pb2.InviteMemeberEmailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'integration_api.SendgridService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('integration_api.SendgridService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SendgridService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WelcomeEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/integration_api.SendgridService/WelcomeEmail',
            sendgrid__api__pb2.WelcomeEmailRequest.SerializeToString,
            sendgrid__api__pb2.WelcomeEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPasswordEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/integration_api.SendgridService/ResetPasswordEmail',
            sendgrid__api__pb2.ResetPasswordEmailRequest.SerializeToString,
            sendgrid__api__pb2.ResetPasswordEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InviteMemberEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/integration_api.SendgridService/InviteMemberEmail',
            sendgrid__api__pb2.InviteMemeberEmailRequest.SerializeToString,
            sendgrid__api__pb2.InviteMemeberEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
